# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "servuno" do |serv|
    serv.vm.box = "puppetlabs/centos-7.0-64-puppet"
    # serv.vm.network "private_network", ip: "192.168.33.10"
  end

  # config.vm.define "server" do |serv|
  #   serv.vm.box = "centos/7"
  #   serv.vm.network "private_network", ip: "192.168.33.20"
  # end

end
