# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 2.0.0"

Vagrant.configure(2) do |config|

  docker_workers = 2
  docker_managers = 3
  mesosphere_workers = 2
  mesosphere_managers = 3
  common_virtualbox_config = Proc.new do |vb|
    vb.customize ['modifyvm', :id, '--memory', '256']
  end

  config.vm.box = 'ubuntu/trusty64'
  config.vm.synced_folder '.', '/vagrant', disabled: true

  docker_workers.times do |i|
    config.vm.define "docker-worker-#{i}" do |cfg|
      cfg.vm.provider :virtualbox do |vb, override|
        common_virtualbox_config.call vb
      end
      cfg.vm.hostname = "docker-worker-#{i}"
      cfg.vm.network 'private_network', ip: "192.168.33.#{20+i}"
    end
  end

  docker_managers.times do |i|
    config.vm.define "docker-manager-#{i}" do |cfg|
      cfg.vm.provider :virtualbox do |vb, override|
        common_virtualbox_config.call vb
      end
      cfg.vm.hostname = "docker-manager-#{i}"
      cfg.vm.network 'private_network', ip: "192.168.33.#{40+i}"
    end
  end

  mesosphere_workers.times do |i|
    config.vm.define "mesosphere-worker-#{i}" do |cfg|
      cfg.vm.provider :virtualbox do |vb, override|
        common_virtualbox_config.call vb
      end
      cfg.vm.hostname = "mesosphere-worker-#{i}"
      cfg.vm.network 'private_network', ip: "192.168.33.#{60+i}"
    end
  end

  mesosphere_managers.times do |i|
    config.vm.define "mesosphere-manager-#{i}" do |cfg|
      cfg.vm.provider :virtualbox do |vb, override|
        common_virtualbox_config.call vb
      end
      cfg.vm.hostname = "mesosphere-manager-#{i}"
      cfg.vm.network 'private_network', ip: "192.168.33.#{80+i}"
    end
  end

  # Executes on the remote machine and returns the hostname
  config.vm.provision :shell, inline: 'hostname'
end
