# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  docker_workers = 2
  common_virtualbox_config = Proc.new do |vb|
    vb.customize ['modifyvm', :id, '--memory', '256']
  end

  config.vm.box = 'ubuntu/trusty64'

  docker_workers.each do |i|
    config.vm.define "docker-worker-#{i}" do |cfg|
      cfg.vm.provider :virtualbox do |vb, override|
        common_virtualbox_config.call vb
      end
      cfg.vm.hostname = "docker-worker-#{i}"
      cfg.vm.network 'private_network', ip: "192.168.33.#{30+i}"
    end
  end

  # config.vm.define 'acs' do |node|
  #   node.vm.hostname = 'acs'
  #   node.vm.network 'private_network', ip: '192.168.33.10'
  # end

  # config.vm.define 'bamboo' do |node|
  #   node.vm.hostname = 'bamboo'
  #   node.vm.network 'private_network', ip: '192.168.33.20'
  #   node.vm.network 'forwarded_port', guest: 80, host: 8080
  # end
  #
  # config.vm.define 'reef' do |node|
  #   node.vm.hostname = 'reef'
  #   node.vm.network 'private_network', ip: '192.168.33.30'
  # end
end
