Vagrant.configure('2') do |config|
  nodes = [1]
  workers = [1]

  config.vm.boot_timeout = 350
  config.vm.box = 'azure'
  config.ssh.private_key_path = '~/.ssh/id_rsa'
  config.vm.synced_folder '.', '/vagrant', disabled: true

  common_azure_config = Proc.new do |azure, override|
    # Mandatory Parameters
    azure.tenant_id = ENV['AZURE_TENANT_ID']
    azure.client_id = ENV['AZURE_CLIENT_ID']
    azure.client_secret = ENV['AZURE_CLIENT_SECRET']
    azure.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']

    # Optional VM Parameters
    azure.resource_group_name = 'dev'
    azure.location = 'westus2'
    azure.vm_size = 'Basic_A0'
    azure.wait_for_destroy = 'true'
    azure.instance_ready_timeout = 180
    azure.instance_check_interval = 3
  end

  nodes.each do |i|
    config.vm.define "node-#{i}" do |cfg|
      cfg.vm.provider :azure do |azure, override|
        common_azure_config.call azure, override
        azure.vm_name = "node-#{i}"
      end
    end
  end

  workers.each do |i|
    config.vm.define "worker-#{i}" do |cfg|
      cfg.vm.provider :azure do |azure, override|
        common_azure_config.call azure, override
        azure.vm_name = "worker-#{i}"
      end
    end
  end

  # Executes on the remote machine and returns the hostname
  config.vm.provision :shell, inline: 'hostname'
end
