Vagrant.configure('2') do |config|
  config.vm.boot_timeout = 350
  config.vm.box = 'azure'
  config.ssh.private_key_path = '~/.ssh/id_rsa'

  common_azure_config = Proc.new do |azure, override|
    # Mandatory Parameters
    azure.tenant_id = ENV['AZURE_TENANT_ID']
    azure.client_id = ENV['AZURE_CLIENT_ID']
    azure.client_secret = ENV['AZURE_CLIENT_SECRET']
    azure.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']

    # Optional VM Parameters
    azure.resource_group_name = 'infra-dev'
    azure.location = 'westus2'
    azure.vm_size = 'Basic_A0'
  end

  config.vm.define :first do |first|
    first.vm.provider :azure do |azure, override|
      common_azure_config.call azure, override
    end
  end

  # Executes on the remote machine and returns the hostname
  config.vm.provision :shell, inline: 'hostname'
end
